global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'town_council_monitor'
    static_configs:
      - targets: ['monitor:8000']

  - job_name: 'town_council_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']

  - job_name: 'town_council_worker'
    static_configs:
      - targets: ['worker:8001']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
